stages:
 - template: azure/stages.yml@templates
   parameters:
     minrust: 1.35.0

resources:
  repositories:
    - repository: templates
      type: github
      name: crate-ci/azure-pipelines
      endpoint: crate-ci
