[package]
name = "imperative"
version = "0.1.0"
authors = ["Ed Page <eopage@gmail.com>"]
description = "Check for imperative mood in text"
repository = "https://github.com/crate-ci/imperative"
documentation = "https://docs.rs/imperative"
readme = "README.md"
categories = ["text-processing"]
license = "MIT"
edition = "2018"

[badges]
travis-ci = { repository = "crate-ci/imperative" }
appveyor  = { repository = "crate-ci/imperative" }

[dependencies]
rust-stemmers = "1.1.0"
phf = "0.7"

[build-dependencies]
phf_codegen = "0.7"
rust-stemmers = "1.1.0"
multimap = "0.5.0"
