[package]
name = "imperative_dev"
version = "1.0.0"
edition = "2021"

[dependencies]
anyhow = { version = "1.0.66" }
clap = { version = "4.0.1", features = ["derive"] }
imperative = { path = ".." }
phf_codegen = "0.11"
rust-stemmers = "1.2.0"
multimap = "0.8.3"
codegenrs = "2.0"
